services:
  issuance-service:
    build:
      context: ./backend/issuance-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: "3001"
      FRONTEND_URL: http://localhost:3000
      VERIFICATION_BASE_URL: http://verification-service:3002
    volumes:
      - issuance_data:/app/data
    networks:
      - kube-credential-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  verification-service:
    build:
      context: ./backend/verification-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: "3002"
      FRONTEND_URL: http://localhost:3000
      ISSUANCE_BASE_URL: http://issuance-service:3001
    networks:
      - kube-credential-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - issuance-service

networks:
  kube-credential-network:
    driver: bridge

volumes:
  issuance_data:
    driver: local