apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-credential-verification
  labels:
    app: kube-credential-verification
    component: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-credential-verification
  template:
    metadata:
      labels:
        app: kube-credential-verification
        component: backend
        version: v1
    spec:
      containers:
      - name: verification-service
        image: kube-credential-verification:latest
        ports:
        - containerPort: 3002
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: FRONTEND_URL
          value: "http://localhost:3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
